### ISSUE TITLE
Full path of file

### ISSUE THREAD

**Issue by ChristianKniep** [kjellkvinge/gocover#10]
Great tool as a single command to generate and easy to use report.
I'd like to use the full path instead of the file name only. 

My project grew quite large and the filename does not identify a file...

### Today

```bash
#filter.go            50.9%
```

### Ideal (for my taste)

```bash
#pkg/library/filter.go            50.9%
```

https://github.com/kjellkvinge/gocover/blob/bec1a9ccf1a4e05a2b53a537272e2492a7e74f92/main.go#L263

**Comment by kjellkvinge** [comment]
Thank you. I think I added support for this in my local branch. I will push this change. I hope this makes the tool better for you 😀
